### ISSUE TITLE
Crashes game

### ISSUE THREAD

**Issue by Graywaren** [ate47/HorseInfo#2]
Tried it on single player as well as trying it as a client side for a vanilla server and it crashed that as well, so isn't working. I've got 1.13.2 and the rift version for that. Tried it with all other mods disabled as well. Crash log says:

Caused by: java.lang.VerifyError: Bad type on operand stackCaused by: java.lang.VerifyError: Bad type on operand stackException Details:  Location:    fr/atesab/horsedebug/HorseDebugMain.renderOverlay()V @56: invokevirtual  Reason:    Type 'akk' (current frame, stack[5]) is not assignable to 'aex'  Current Frame:    bci: @56    flags: { }    locals: { 'fr/atesab/horsedebug/HorseDebugMain', 'cfi', 'cfs', 'akk' }    stack: { 'fr/atesab/horsedebug/HorseDebugMain', 'cfi', integer, integer, 'fr/atesab/horsedebug/HorseDebugMain', 'akk' }  Bytecode:    0x0000000: b801 594c 2bb4 015d b401 629a 0004 b12b    0x0000010: b400 774d 2bb4 0165 b601 6bc1 00ba 9900    0x0000020: 242b b401 65b6 016b c000 ba4e 2a2b 2cb6    0x0000030: 007d 2cb6 0080 2a2d b601 6d2d b601 6fa7    0x0000040: 0042 2bb4 0172 4e2d c600 392d b401 75b2    0x0000050: 0177 b601 7a99 002c 2db4 017d c100 a999    0x0000060: 0022 2a2b 2cb6 007d 2cb6 0080 2a2d b401    0x0000070: 7dc0 00a9 b601 6d2d b401 7dc0 00a9 b601    0x0000080: 6fb1                                     Stackmap Table:    append_frame(@15,Object[#103])    append_frame(@66,Object[#121])    same_frame(@129)
at fr.atesab.horsedebug.RiftHorseDebug.<init>(RiftHorseDebug.java:10) ... 27 more

**Comment by Graywaren** [comment]
I have also tried it on a fresh instance of 1.13.2 & Rift as the only mod installed and it does the same thing.

**Comment by szwip** [comment]
Same problem:

```
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    fr/atesab/horsedebug/HorseDebugMain.renderOverlay()V @56: invokevirtual
  Reason:
    Type 'akk' (current frame, stack[5]) is not assignable to 'aex'
  Current Frame:
    bci: @56
    flags: { }
    locals: { 'fr/atesab/horsedebug/HorseDebugMain', 'cfi', 'cfs', 'akk' }
    stack: { 'fr/atesab/horsedebug/HorseDebugMain', 'cfi', integer, integer, 'fr/atesab/horsedebug/HorseDebugMain', 'akk' }
  Bytecode:
    0x0000000: b801 594c 2bb4 015d b401 629a 0004 b12b
    0x0000010: b400 774d 2bb4 0165 b601 6bc1 00ba 9900
    0x0000020: 242b b401 65b6 016b c000 ba4e 2a2b 2cb6
    0x0000030: 007d 2cb6 0080 2a2d b601 6d2d b601 6fa7
    0x0000040: 0042 2bb4 0172 4e2d c600 392d b401 75b2
    0x0000050: 0177 b601 7a99 002c 2db4 017d c100 a999
    0x0000060: 0022 2a2b 2cb6 007d 2cb6 0080 2a2d b401
    0x0000070: 7dc0 00a9 b601 6d2d b401 7dc0 00a9 b601
    0x0000080: 6fb1                                   
  Stackmap Table:
    append_frame(@15,Object[#103])
    append_frame(@66,Object[#121])
    same_frame(@129)

	at fr.atesab.horsedebug.RiftHorseDebug.<init>(RiftHorseDebug.java:10) ~[RiftHorseDebug.class:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at org.dimdev.riftloader.RiftLoader.newInstance(RiftLoader.java:284) ~[RiftLoader.class:?]
	at org.dimdev.riftloader.RiftLoader.loadListeners(RiftLoader.java:264) ~[RiftLoader.class:?]
	... 13 more
```

**Comment by Stupid-name123** [comment]
I get that if I use 1.13.2 
pls update mod

**Comment by I-made-this-to-tag-you** [comment]
@ate47 pls update mod to 1.13.2

**Comment by ate47** [comment]
Rift version not supported anymore, use the Fabric or Forge version
